### ISSUE TITLE
okex SWAP fetchOpenOrders and cancelOrder issue

### ISSUE THREAD

**Issue by gavin369** [ccxt/ccxt#7319]
Use version1.31.61

```
async function main() {

    await this_.exchanges[0].cancelOrder(548281388053248000,'TRX-USD-SWAP')

}
```

Spot is OK, not SWAP，Returns the following error。

`TypeError: this[method] is not a function
    at okex.cancelOrder (index.js:85943)
    at async main (eval at _callee3$ (selector.js?type=script&index=0!./src/components/component/localbot.vue:NaN), <anonymous>:487:5)`

**Comment by kroitor** [comment]
@gavin369 I'll look into it and will fix shortly. Thx for reporting!

**Comment by kroitor** [comment]
@gavin369 a quick question, how do you initialize the exchange?

**Comment by kroitor** [comment]
This should work fine in CCXT as of version 1.31.64+, the new build will arrive in 15 minutes. Let us know if you have further difficulties with it after upgrading to the most recent version. Thx for the feedback!
