### PR TITLE
Batch 9 PRs: #30448, #30446, #30443, #30436

### PR DESCRIPTION
**Pull request by carlotestor**
## Summary

Automated daily batch: 9 independently-reviewed fixes. Each source PR was re-reviewed by an Opus 5 leaf that was allowed to add carlotestor-authored correctness commits on top of the original author's work. Every source PR passed its merge gate (🟢), stayed within 6 files / 400 changed lines, and the file sets are mutually disjoint.

This PR **closes** all of the PRs below automatically on merge.

| PR | Author | Files | Change |
|---|---|---|---|
| Closes #30448 | @AresArtemius | `ts/src/bingx.ts, ts/src/test/base/language_specific/test.bingxTestOrder.ts, ts/src/test/base/language_specific/test.languageSpecific.ts` | fix(bingx): reject test orders for unsupported markets |
| Closes #30446 | @AresArtemius | `skip-tests.json` | test(extended): allow intentionally retained spot markets |
| Closes #30443 | @AresArtemius | `ts/src/deepcoin.ts, ts/src/test/static/response/deepcoin.json` | fix(deepcoin): omit zero ticker timestamps |
| Closes #30436 | @rayBastard | `ts/src/pro/okx.ts` | fix(okx): declare has.unWatch* flags for implemented methods |
| Closes #30427 | @rayBastard | `ts/src/pacifica.ts, ts/src/test/static/request/pacifica.json, ts/src/test/static/response/pacifica.json` | fix(pacifica): fetchBalance returned empty free/used/total |
| Closes #30037 | @carlotestor | `ts/src/hyperliquid.ts` | fix(hyperliquid): raise InvalidOrder when a positive amount rounds to zero |
| Closes #29892 | @rayBastard | `ts/src/krakenfutures.ts, ts/src/test/static/request/krakenfutures.json` | fix(krakenfutures): guard null price in createOrderRequest |
| Closes #29219 | @ttodua | `build/transpile.ts, php/test/tests_async.php, php/test/tests_helpers.php, php/test/tests_sync.php` | test(php): allow isolated sync |
| Closes #29133 | @vsaraikin | `go/tests/exchange_cache_race_test.go, go/v4/exchange_cache.go` | fix(go): copy-on-write merge in ArrayCache to fix concurrent map read/write in WatchOrders |

Original authorship is preserved in the merge commits. Any additional commits on a source branch were authored as carlotestor to address unresolved carlotestor review comments (regressions, missing tests, correctness).

## How this was built

```
# per-PR worktree off origin/master, merge original PR head, then a leaf
# may add carlotestor commits. Then:
git checkout -b batch/small-fixes-20260915 origin/master
git merge --no-ff rev/pr<N>-20260915
```

## Diff

```
 build/csharpTranspiler.ts                          |   2 +-
 build/goTranspiler.ts                              |   1 +
 build/javaTranspiler.ts                            |   2 +-
 build/transpile.ts                                 |   9 +-
 cs/ccxt/ws/ArrayCache.cs                           |  96 +++++++
 go/v4/exchange_cache.go                            |  73 ++++--
 go/v4/exchange_cache_race_test.go                  | 127 +++++++++
 go/v4/exchange_cache_removesymbol_test.go          |  81 ++++++
 .../main/java/io/github/ccxt/ws/ArrayCache.java    |  96 ++++++-
 php/pro/ArrayCache.php                             |  63 +++++
 php/pro/ArrayCacheBySymbolById.php                 |  14 +
 php/pro/ArrayCacheBySymbolBySide.php               |  14 +
 php/test/tests_async.php                           |   2 +-
 php/test/tests_helpers.php                         |  13 +-
 php/test/tests_sync.php                            |   4 +-
 python/ccxt/async_support/base/ws/cache.py         |  53 ++++
 skip-tests.json                                    |   7 +-
 ts/src/base/ws/Cache.ts                            |  35 +++
 ts/src/bingx.ts                                    |   5 +-
 ts/src/deepcoin.ts                                 |   2 +-
 ts/src/hyperliquid.ts                              |   9 +-
 ts/src/krakenfutures.ts                            |   9 +-
 ts/src/pacifica.ts                                 |  64 +++--
 ts/src/pro/bingx.ts                                |   9 +
 .../pro/test/base/test.bingxPositionTransitions.ts | 101 ++++++++
 ts/src/pro/test/base/tests.init.ts                 |   2 +
 .../base/language_specific/test.bingxTestOrder.ts  |  62 +++++
 .../language_specific/test.languageSpecific.ts     |   2 +
 ts/src/test/static/request/krakenfutures.json      |  27 ++
 ts/src/test/static/request/pacifica.json           |   2 +-
 ts/src/test/static/response/deepcoin.json          | 286 +++++++++++++++++++++
 ts/src/test/static/response/pacifica.json          |  95 +++++--
 32 files changed, 1282 insertions(+), 85 deletions(-)
```

## Verification

- JSON files parse
- `tsc --noEmit`: no new errors (1 pre-existing on master at merge-base `1b606ef7632`, byte-identical)
- All branches merged with `--no-ff`, no conflicts
- Diff limited to the files above — no generated output committed

## Notes

Opened by the daily `ccxt-daily-pr-batch` job on the `ccxt-webhook` (Opus 5) profile. Per-PR review discussion stays on the original threads.

### CODE REVIEW

**Comment by carlotestor** [comment]
## `java.yml` `build` is red — batch finding, root cause below

Reporting against this batch honestly: **this is the batch's own finding, not upstream breakage.** 4 of the 7 `build` jobs are green (`js`, `python`, `php`, `cs`); `java` failed; `go-app` and `rust` were still running.

### The failure

```
java/lib/src/main/java/io/github/ccxt/exchanges/pro/Bingx.java:1709: error: cannot find symbol
                cache.removeSymbol(symbol);
                     ^
  symbol:   method removeSymbol(String)
  location: variable cache of type Object
```

Failing step is **Build Project** (step 13); every later step reports `skipped`, so a plain `grep error` over the log looks deceptively quiet.

### Root cause

`#30447` adds a `removeSymbol()` method to the hand-written WS cache bases and calls it from `ts/src/pro/bingx.ts:1393`:

```ts
cache.removeSymbol (symbol);
```

`cache` is a **local variable**, so in the emitted Java it is typed `Object` and the call needs to go through `Helpers.callDynamically`. The C# transpiler was updated for this (`build/csharpTranspiler.ts`, the `append|resolve|getLimit|removeSymbol` alternation) — which is why **`cs` build passes** — but the Java transpiler has its *own* dispatch list that was not updated:

```ts
// build/javaTranspiler.ts:3394
const dynamicMethods = ['append', 'reset', 'storeArray', 'store', 'getLimit'];

// build/javaTranspiler.ts:3403 — only this.<field>, only these four methods
content = content.replace(/this\.(myTrades|positions|orders|trades|ohlcvs|tickers|orderbooks)\.(append|store|storeArray|reset)\(/gm, …)
```

Neither path covers `removeSymbol`, and neither covers a call on a **local** binding rather than a `this.<field>`, so the call is emitted verbatim against an `Object` receiver.

### Why local verification missed it

The hand-written `java/lib/.../ws/ArrayCache.java` base compiles fine on its own (its gradle tests pass). The break is only in the **transpiled** `pro/Bingx.java` that *calls* it — i.e. compiling the base is not sufficient evidence; the generated exchange file has to be compiled too.

### Not merging

Per our batch policy we do not merge, close, or rewrite on a red gate. This PR stays open with the diagnosis attached so the fix can land deliberately — the Java dispatch needs `removeSymbol` handled for local (`Object`-typed) receivers, mirroring the C# side.

<sub>Posted by the daily `ccxt-daily-pr-batch` job.</sub>

**Comment by AresArtemius** [comment]
Fixed in AresArtemius/ccxt@95eadda1576. Added removeSymbol to Java’s local-variable dynamic dispatch list. Verified against this batch head: regenerated Bingx.java compiles, and both offline position-transition scenarios pass. Please cherry-pick the commit into the batch.

**Comment by carlotestor** [comment]
**Update: PR #30447 dropped from this batch.**

`batch/small-fixes-20260915` was rebuilt from `origin/master` by replaying the remaining merges (`--no-ff`, original merge messages). No conflicts. New head is `8168f9b679f` (was `b99c742e428`), and the diff is now **18 files, +683/−72** (previously 27 files).

#30447 stays open and will be considered for a future batch.

### Updated batch contents

| PR | Author | Files | Change |
|---|---|---|---|
| Closes #30448 | @AresArtemius | `ts/src/bingx.ts, ts/src/test/base/language_specific/test.bingxTestOrder.ts, ts/src/test/base/language_specific/test.languageSpecific.ts` | fix(bingx): reject test orders for unsupported markets |
| Closes #30446 | @AresArtemius | `skip-tests.json` | test(extended): allow intentionally retained spot markets |
| Closes #30443 | @AresArtemius | `ts/src/deepcoin.ts, ts/src/test/static/response/deepcoin.json` | fix(deepcoin): omit zero ticker timestamps |
| Closes #30427 | @rayBastard | `ts/src/pacifica.ts, ts/src/test/static/request/pacifica.json, ts/src/test/static/response/pacifica.json` | fix(pacifica): fetchBalance returned empty free/used/total |
| Closes #30037 | @carlotestor | `ts/src/hyperliquid.ts` | fix(hyperliquid): raise InvalidOrder when a positive amount rounds to zero |
| Closes #29892 | @rayBastard | `ts/src/krakenfutures.ts, ts/src/test/static/request/krakenfutures.json` | fix(krakenfutures): guard null price in createOrderRequest |
| Closes #29219 | @ttodua | `build/transpile.ts, php/test/tests_async.php, php/test/tests_helpers.php, php/test/tests_sync.php` | test(php): allow isolated sync |
| Closes #29133 | @vsaraikin | `go/v4/exchange_cache.go, go/v4/exchange_cache_race_test.go` | fix(go): copy-on-write merge in ArrayCache to fix concurrent map read/write in WatchOrders |

### Note on #30436

#30436 (`fix(okx): declare has.unWatch* flags`) was **merged upstream separately** on 2026-09-15. Its merge commit is still on this branch for provenance, but it now contributes **zero files** — `ts/src/pro/okx.ts` here is identical to master. So this batch carries 8 PRs' worth of actual changes.

File sets remain mutually disjoint; every remaining source PR was gate-🟢 at selection time.

**Comment by carlotestor** [comment]
## Merge digest

Nine independently-reviewed fixes batched together: balance parsing, order validation, WS flags, and a Go ArrayCache race.

| File | Δ | What |
| --- | ---: | --- |
| `ts/src/pacifica.ts` | +43/−21 | `fetchBalance` free/used/total |
| `ts/src/hyperliquid.ts` | +8/−1 | `createOrder` amount rounds to zero |
| `ts/src/krakenfutures.ts` | +8/−1 | `createOrderRequest` null price |
| `ts/src/bingx.ts` | +4/−1 | test-order market guard |
| `ts/src/deepcoin.ts` | +1/−1 | zero ticker timestamp |
| (13 more files) | +619/−47 | tests, ports, transpiler |

```mermaid
flowchart LR
  safeInteger["safeInteger"]
  deepcoin["deepcoin"]
  deepcoin -.inlined.-> safeInteger
```

`ts/src/pacifica.ts`

```ts
@@ -832,15 +846,23 @@
-        result['free'] = {};
-        result['used'] = {};
-        result['total'] = {};
-        const totalBalance = this.safeNumber (data, 'account_equity');
-        const usedMargin = this.safeNumber (data, 'total_margin_used');
-        const freeBalance = this.safeNumber (data, 'available_to_spend');
-        result['total']['USDC'] = totalBalance;
-        result['used']['USDC'] = usedMargin;
-        result['free']['USDC'] = freeBalance;
+        const usdcAccount = this.account ();
+        usdcAccount['total'] = this.safeString (data, 'balance');
+        usdcAccount['used'] = this.safeString (data, 'total_margin_used');
+        result['USDC'] = usdcAccount;
```
