### ISSUE TITLE
Should Gate.io fetch_open_orders() really require a symbol argument?

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13223]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.82.19

```
exchange = ccxt.gateio({...})
exchange.fetch_open_orders()
```

```
Traceback (most recent call last):
...
    exchange.fetch_open_orders()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/gateio.py", line 3099, in fetch_open_orders
    return self.fetch_orders_by_status('open', symbol, since, limit, params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/gateio.py", line 3124, in fetch_orders_by_status
    raise ArgumentsRequired(self.id + ' fetchOrdersByStatus requires a symbol argument for spot non-stop open orders')
ccxt.base.errors.ArgumentsRequired: gateio fetchOrdersByStatus requires a symbol argument for spot non-stop open orders
```

`fetch_open_orders` was working without symbol argument until today when I updated ccxt to the most recent version. According to Gate.io API documentation it should be possible to fetch open orders without a currency pair argument: https://www.gate.io/docs/developers/apiv4/en/#list-all-open-orders

Is Gate.io about to change the symbol requirement or is there some other reason for now requiring the symbol on the ccxt side or is this a bug?

**Comment by kroitor** [comment]
@JovianMoon thx for reporting it! Please, let us know if you have this issue with CCXT 1.82.23+ (the new build will arrive in ~20 minutes). Appreciate your feedback!

**Comment by samgermain** [comment]
> @JovianMoon thx for reporting it! Please, let us know if you have this issue with CCXT 1.82.23+ (the new build will arrive in ~20 minutes). Appreciate your feedback!

Parsing the response wasn't done correctly, I fixed that in this PR https://github.com/samgermain/ccxt/commit/91289135d4ba9d7ec6b303847c30fbf0c69c52d1

**Comment by JovianMoon** [comment]
@kroitor @samgermain Still not working with 1.82.32:

```
Traceback (most recent call last):
...
    reply = self.exchange.fetch_open_orders()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/gateio.py", line 3099, in fetch_open_orders
    return self.fetch_orders_by_status('open', symbol, since, limit, params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/gateio.py", line 3266, in fetch_orders_by_status
    result = result.concat(orders)
AttributeError: 'list' object has no attribute 'concat'
```

**Comment by JovianMoon** [comment]
Seems to be working fine now with 1.82.33
