### ISSUE TITLE
GO: CCXT (tagged versions) vs CCXT/PRO (untagged versions)

### ISSUE THREAD

**Issue by csotto** [ccxt/ccxt#27630]
### Operating System

WIndos and Linux

### Programming Language

GO

### CCXT Version

v4.4.64 & v4.5.30

### Description

Using GO PRO has frequently generated unexpected compilation results. I suspect the problem may be the lack of tagged version numbers in GO PRO code.

We all know, and understand that GO CCXT & PRO are undergoing an intense coding effort, which can be translated to pulling an intermediate (between two tagged versions) from Github may be unsafe. So I try to use only tagged versions.

I could not find and pull a release tagged version for CCXT/PRO (WS). when a tagged version is missing go creates a pseudo-version **pseudo-version** like v0.0.0-20251030144611-ae08284a459d but is not enough.

To better expose the problem I am addressing I chose the Go cli app at **(github.com/ccxt/ccxt/go/cli)**. Pull it and cd into cli folder. not changing a single line,

Go cli app **comes with go.mod** file that nails the Compiler and Packages versions necessary for build. 
As these versions are older than what I have on my computer decided to issue **go clean -cache -modcache -fuzzcache -testcache** to erase any traces of a most recent versions I could have in my notebook.

Then already in cli directory I issue a **go run .** ... And waited about 6 minutes until go completed pulling the historical versions of the compiler, CCXT and other packages for the versions stated in go mod file. The result was failure to compile. (compiler error snippets are far down)

QUESTION: What is the version of the CCXT PRO that will match and compile with CCXT v4.4.64?

I tried to pull CCXT PRO version v4.4.64 with no results.**(error snippets are far down)**. 
Also tried using lates CCXT release, version v4.5.30. 
Tried to pull CCXT PRO at the desired version. **(error snippets are far down)**.
No succes in any of the attempts.

What should be the PRO VERSION that I should use? 

====== Code and error snippets ======

``` 
COULD NOT PULL A CORRESPONDING VERSION FOR github.com/ccxt/ccxt/go/v4/pro
$ go get github.com/ccxt/ccxt/go/v4/pro@v4.4.64
go: module github.com/ccxt/ccxt/go/v4@v4.4.64 found, but does not contain package github.com/ccxt/ccxt/go/v4/pro
```

``` 
THE GO.MOD VERSIONS
module github.com/ccxt/cli
go 1.24.4
require (
	github.com/ccxt/ccxt/go/v4 v4.4.64
	github.com/ccxt/ccxt/go/v4/pro v0.0.0-20251030144611-ae08284a459d
)
require (
	github.com/bits-and-blooms/bitset v1.20.0 // indirect
             …...
             …...
```

```
THE ERRORS
$ go run .
# github.com/ccxt/ccxt/go/v4/pro
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\alpaca.go:8:8: undefined: ccxt.AlpacaCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\alpaca.go:9:13: undefined: ccxt.AlpacaCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\apex.go:8:8: undefined: ccxt.ApexCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\apex.go:9:13: undefined: ccxt.ApexCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\apex_wrapper.go:6:24: undefined: ccxt.Apex
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\arkham.go:8:8: undefined: ccxt.ArkhamCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\arkham.go:9:13: undefined: ccxt.ArkhamCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\arkham_wrapper.go:6:24: undefined: ccxt.Arkham
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\ascendex.go:8:8: undefined: ccxt.AscendexCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\ascendex.go:9:13: undefined: ccxt.AscendexCore
D:\.gomodcache\github.com\ccxt\ccxt\go\v4\pro@v0.0.0-20251030144611-ae08284a459d\ascendex.go:9:13: too many errors

```

Thanks for your attention.

**Comment by csotto** [comment]
Let me add a comment to initial issue dscription: The test using current (v4.5.30) version was carried out using: 

1. a reduced go.mod file (see below) containig only latest compiler version and ccxt version v4.5.30;
2. calling **go mod tidy** - to let go build the correct available package versions, before compiling.

This also resulted in compile errors.

```
THE REDUCED GO.MOD FILE
module github.com/ccxt/cli
go 1.25.5
require (
	github.com/ccxt/ccxt/go/v4 v4.5.30
)
```

**Comment by carlosmiei** [comment]
Hello @csotto, first of all, thanks for reporting it.

Both the CCXT and CCXT Pro versions should be completely aligned we don't do different releases, we will take a look and get back to you.
