### PR TITLE
fix(rust): compile test.fetchTrades after #30381 (async helper + groupBy)

### PR DESCRIPTION
**Pull request by carlotestor**
## Problem

The `Rust` workflow on master fails at **Build** since #30381 landed `test.fetchTrades.ts` changes (run [35212638722](https://github.com/ccxt/ccxt/actions/runs/35212638722)):

```
error[E0599]: no method named `group_by` found for enum `ccxt::Value` in the current scope
  --> tests/src/../exchange/test.fetchTrades.rs:37:43
error[E0277]: `ccxt::Value` is not a future
  --> tests/src/../exchange/test.fetchTrades.rs:46:136
   |    helperTestFetchTradesSideSequence(...).await;
error: could not compile `ccxt_tests` (bin "ti-rust") due to 2 previous errors
```

## Root cause

1. `exchange.groupBy (trades, 'side')` — the transpiled tests call exchange helpers through the hand-written `ExchangeOps` trait on `Value` (`rust/tests/src/test_helpers.rs`), and it had no `group_by`.
2. `async function helperTestFetchTradesSideSequence (...)` has no `await` inside its body. The AST drops `async`, and every re-marking pass in `rustTranspiler.ts` (`markMethodsAsyncIfBodyAwaits` + the belt-and-braces regex) only re-adds it when the body contains `.await`. So the helper was emitted as a sync `fn` while the caller kept `.await`.

## Fix

- `test_helpers.rs`: add `group_by` to `ExchangeOps`, delegating to `Exchange::group_by` like `index_by`.
- `rustTranspiler.ts`: in `transpileExchangeTests`, read the `async function` names straight from the TS source (`detectFreeAsyncFns`) and mark them `async fn` (`markFreeFnsAsync`) regardless of body content, so the declaration follows the TS signature rather than a body heuristic.
- Regenerated `rust/tests/exchange/test.fetchTrades.rs`.

## Verification

`npx tsx build/rustTranspiler.ts --tests` regenerates the file with `async fn helperTestFetchTradesSideSequence` and `exchange.group_by(...)`; `cargo build --manifest-path rust/Cargo.toml` (incl. `ccxt_tests`) is green on the build host with this branch.

### CODE REVIEW

**Comment by carlotestor** [comment]
## Merge digest

Fixes the Rust build broken by #30381 by adding `group_by` to `ExchangeOps` and marking free `async function` helpers as `async fn` from the TS signature instead of a body heuristic.

| File | Δ | What |
| --- | ---: | --- |
| `build/rustTranspiler.ts` | +27/−0 | `detectFreeAsyncFns`, `markFreeFnsAsync` |
| `ts/src/test/tests.ts` | +4/−0 | `safeString` |
| `rust/tests/src/test_helpers.rs` | +2/−0 | `group_by` on `ExchangeOps` |
| `ts/src/test/static/ws/okx.json` | +1/−0 | ws fixture entry |
| (1 generated/other) | +79/−3 | regenerated `test.fetchTrades.rs` |

```mermaid
flowchart LR
  test_fetchTrades_rs["test.fetchTrades.rs"]
  tests["tests"]
  safeString["safeString"]
  detectFreeAsyncFns["detectFreeAsyncFns"]
  markFreeFnsAsync["markFreeFnsAsync"]
  markFreeFnsAsync --> detectFreeAsyncFns
  tests --> safeString
  test_fetchTrades_rs --> tests
```

`build/rustTranspiler.ts`

```ts
@@ -8334,6 +8334,32 @@
+    detectFreeAsyncFns(tsSrc: string): Set<string> {
+        const out = new Set<string>();
+        const re = /\basync\s+function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/g;
+        let m: RegExpExecArray | null;
+        while ((m = re.exec(tsSrc)) !== null) out.add(m[1]);
+        return out;
+    }
+    markFreeFnsAsync(content: string, names: Set<string>): string {
+        for (const name of names) {
+            content = content.replace(
+                new RegExp(`(^|\\n)(\\s*)((?:pub\\s+)?)fn\\s+${name}\\s*\\(`),
+                (_full, before, indent, pub_) => `${before}${indent}${pub_}async fn ${name}(`,
+            );
```
