### ISSUE TITLE
import ccxt.async_support as accxt error

### ISSUE THREAD

**Issue by bitProfessor** [ccxt/ccxt#4752]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:python
- CCXT version: 1.18.296
- Exchange:
- Method:
mycode:
import ccxt.async_support as accxt
print(ccxt.exchanges)
Traceback (most recent call last):
  File "/Users/jacking/Desktop/test.py", line 1, in <module>
    import ccxt.async_support as accxt
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/__init__.py", line 11, in <module>
    from ccxt.async_support.base.exchange import Exchange                   # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/base/__init__.py", line 4, in <module>
    from ccxt.async_support.base import exchange
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 16, in <module>
    import aiohttp
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/helpers.py", line 74, in <module>
    all_tasks = getattr(asyncio, 'all_tasks')  # noqa
AttributeError: module 'asyncio' has no attribute 'all_tasks'

**Comment by kroitor** [comment]
@bitProfessor you're not showing your complete code. The code you posted works on my system with Python 3.7.2 and CCXT 1.18.296:

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt.async_support as ccxt
>>> print(ccxt.exchanges)
['_1btcxe', 'acx', 'allcoin', 'anxpro', 'anybits', 'bcex', 'bibox', 'bigone', 'binance', 'bit2c', 'bitbank', 'bitbay', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitforex', 'bithumb', 'bitibu', 'bitkk', 'bitlish', 'bitmarket', 'bitmex', 'bitsane', 'bitso', 'bitstamp', 'bitstamp1', 'bittrex', 'bitz', 'bl3p', 'bleutrade', 'braziliex', 'btcalpha', 'btcbox', 'btcchina', 'btcexchange', 'btcmarkets', 'btctradeim', 'btctradeua', 'btcturk', 'buda', 'bxinth', 'ccex', 'cex', 'chbtc', 'chilebit', 'cobinhood', 'coinbase', 'coinbaseprime', 'coinbasepro', 'coincheck', 'coinegg', 'coinex', 'coinexchange', 'coinfalcon', 'coinfloor', 'coingi', 'coinmarketcap', 'coinmate', 'coinnest', 'coinone', 'coinspot', 'cointiger', 'coolcoin', 'coss', 'crex24', 'crypton', 'cryptopia', 'deribit', 'dsx', 'ethfinex', 'exmo', 'exx', 'fcoin', 'flowbtc', 'foxbit', 'fybse', 'fybsg', 'gatecoin', 'gateio', 'gdax', 'gemini', 'getbtc', 'hadax', 'hitbtc', 'hitbtc2', 'huobipro', 'huobiru', 'ice3x', 'independentreserve', 'indodax', 'itbit', 'jubi', 'kkex', 'kraken', 'kucoin', 'kucoin2', 'kuna', 'lakebtc', 'lbank', 'liqui', 'liquid', 'livecoin', 'luno', 'lykke', 'mercado', 'mixcoins', 'negociecoins', 'nova', 'okcoincny', 'okcoinusd', 'okex', 'paymium', 'poloniex', 'quadrigacx', 'rightbtc', 'southxchange', 'stronghold', 'surbitcoin', 'theocean', 'therock', 'tidebit', 'tidex', 'uex', 'upbit', 'urdubit', 'vaultoro', 'vbtc', 'virwox', 'xbtce', 'yobit', 'yunbi', 'zaif', 'zb']
```

> * all_tasks = getattr(asyncio, 'all_tasks')  # noqa

This line ↑ is from an example and it is missing from the code you posted.

We need the complete snippet from you to reproduce the issue. Also, when posting, please follow these guides **precisely** and format the code/output for readability: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue.

Waiting for a followup from you on this.

**Comment by kroitor** [comment]
@bitProfessor there's an error in your code:

```Python
import ccxt.async_support as accxt  # you import it as "accxt"
print(ccxt.exchanges)  # and then you reference it as "ccxt", not "accxt"
```

Let us know if that does not answer the question.

**Comment by kroitor** [comment]
```
$ cat composer.json && composer why-not ccxt/ccxt 1.18.296
{
    "name": "igorkroitor/composer-test",
    "authors": [
        {
            "name": "Igor Kroitor",
            "email": "igor.kroitor@gmail.com"
        }
    ],
    "require": {
        "ccxt/ccxt": "1.18.296"
    }
}
There is no installed package depending on "ccxt/ccxt" in versions not matching 1.18.296
```

**Comment by bitProfessor** [comment]
Python 3.7.0a2 (v3.7.0a2:f7ac4fe52a, Oct 16 2017, 21:11:18) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt.async_support as accxt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/__init__.py", line 11, in <module>
    from ccxt.async_support.base.exchange import Exchange                   # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/base/__init__.py", line 4, in <module>
    from ccxt.async_support.base import exchange
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 16, in <module>
    import aiohttp
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aiohttp/helpers.py", line 74, in <module>
    all_tasks = getattr(asyncio, 'all_tasks')  # noqa
AttributeError: module 'asyncio' has no attribute 'all_tasks'

**Comment by kroitor** [comment]
@bitProfessor what's your version of asyncio?

**Comment by bitProfessor** [comment]
an error when import,not my code

**Comment by kroitor** [comment]
@bitProfessor what's your version of aiohttp?

**Comment by bitProfessor** [comment]
i will check up,just a m...

**Comment by bitProfessor** [comment]
aiodns (1.1.1)
aiohttp (3.5.4)
appdirs (1.4.3)
asn1crypto (0.24.0)
async-timeout (3.0.1)
attrs (18.2.0)
bitshares (0.1.11)
ccxt (1.18.296)

**Comment by bitProfessor** [comment]
aiohttp 3.5.4

**Comment by kroitor** [comment]
@bitProfessor can you try updating Python to a non-alpha version? I'd recommend a stable 7.3.2. I'm almost sure it's because of it.

**Comment by bitProfessor** [comment]
ok,i'll try

**Comment by kroitor** [comment]
@bitProfessor let me know if that doesn't help

**Comment by bitProfessor** [comment]
it's works,thank you

**Comment by bitProfessor** [comment]
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt.async_support as accxt
>>>

**Comment by kroitor** [comment]
@bitProfessor thanks for reporting back! Looks like Python 3.7.0a2 wasn't a very stable release, indeed.

**Comment by bitProfessor** [comment]
yes
