### ISSUE TITLE
Python 3 Broken

### ISSUE THREAD

**Issue by timolson** [ccxt/ccxt#3480]
This test file:
```
import sys
import ccxt

print(sys.version)
print(ccxt.__version__)
exchange = ccxt.binance()
exchange.fetch_ohlcv('BTC/USDT','1m')
```
results in the error:
```
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
1.17.4
Traceback (most recent call last):
  File "/home/tim/code/ct2/test.py", line 7, in <module>
    exchange.fetch_ohlcv('BTC/USDT','1m')
  File "/opt/ct2-venv/lib/python3.5/site-packages/ccxt/binance.py", line 499, in fetch_ohlcv
    response = self.publicGetKlines(self.extend(request, params))
  File "/opt/ct2-venv/lib/python3.5/site-packages/ccxt/binance.py", line 904, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/opt/ct2-venv/lib/python3.5/site-packages/ccxt/base/exchange.py", line 318, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/opt/ct2-venv/lib/python3.5/site-packages/ccxt/binance.py", line 852, in sign
    url += '?' + self.urlencode(params)
  File "/opt/ct2-venv/lib/python3.5/site-packages/ccxt/base/exchange.py", line 631, in urlencode
    return _urlencode.urlencode(params)
AttributeError: module 'urllib' has no attribute 'urlencode'
```
`urlencode` has been moved to `urllib.parse.urlencode()` in Python 3.

**Comment by kroitor** [comment]
> urlencode has been moved to urllib.parse.urlencode() in Python 3.

Yep it has been moved in Python 3: https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L69

Will look into this shortly.

**Comment by timolson** [comment]
I got it to work with Python 3.6.2, but even a fresh virtualenv of 3.5.2 continues to break.

The problem appears with `1.17.1`, while `1.16.89` works.

```
(p35) tim@blossom:~/code/ct2$ pip install ccxt==1.16.89
[...]
Successfully installed ccxt-1.16.89
(p35) tim@blossom:~/code/ct2$ python test.py 
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
1.16.89
(p35) tim@blossom:~/code/ct2$ pip install ccxt==1.17.1
[...]
Successfully installed ccxt-1.17.1
(p35) tim@blossom:~/code/ct2$ python test.py 
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
1.17.1
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    exchange.fetch_ohlcv('BTC/USDT','1m')
  File "/home/tim/code/ct2/p35/lib/python3.5/site-packages/ccxt/bitfinex.py", line 743, in fetch_ohlcv
    response = self.v2GetCandlesTradeTimeframeSymbolHist(self.extend(request, params))
  File "/home/tim/code/ct2/p35/lib/python3.5/site-packages/ccxt/base/exchange.py", line 322, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/tim/code/ct2/p35/lib/python3.5/site-packages/ccxt/base/exchange.py", line 318, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/tim/code/ct2/p35/lib/python3.5/site-packages/ccxt/bitfinex.py", line 823, in sign
    suffix = '?' + self.urlencode(query)
  File "/home/tim/code/ct2/p35/lib/python3.5/site-packages/ccxt/base/exchange.py", line 631, in urlencode
    return _urlencode.urlencode(params)
AttributeError: module 'urllib' has no attribute 'urlencode'
```


Reviewing the code, maybe the problem is not with urlencode but with Web3:
```
try:
    import urllib.parse as _urlencode    # Python 3
    # from web3.auto import w3             # web3/0x imports
    from web3 import Web3, HTTPProvider
except ImportError:
    import urllib as _urlencode          # Python 2
Web3 = HTTPProvider = None # web3/0x not supported in Python 2
```

If there were any error importing `Web3` or `HTTPProvider`, it would cause the problem I'm seeing, due to the bad package mapping that would result from the exception catch.  Were there any changes to the Web3/HTTPProvider stuff for `1.17.1`?  Perhaps something which assumes Python 3.6+?

I can update to Python 3.6 as a workaround, but there is maybe a deeper bug here you want to look at.

**Comment by kroitor** [comment]
> Were there any changes to the Web3/HTTPProvider stuff for 1.17.1? Perhaps something which assumes Python 3.6+?

Yep, exactly. The version bump was there because of adding Web3. Case solved, apparently. Thx for pointing that out! Let me know if you still have difficulties with it after updating to 1.17.6.
