### ISSUE TITLE
One time Fetching of orderbook for all symbols

### ISSUE THREAD

**Issue by l0urdm** [ccxt/ccxt#1930]
is there a way to fetch the best bid and ask price and amount for all markets in one go?

I'm using cryptopia and this doesn't seem to work or maybe I'm using a wrong syntax:

orderbook = cryptopia.fetch_order_book (cryptopia.symbols[0])

I was expecting it will return the bid and ask amount and price for all markets but I get this error: TypeError: 'NoneType' object has no attribute '__getItem__'

I'm using python 2.7,14

**Comment by kroitor** [comment]
> is there a way to fetch the best bid and ask price and amount for all markets in one go?

Currently, just a few exchanges support fetching all order books at once. See the `had['fetchOrderBooks']` property, documented here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

> I was expecting it will return the bid and ask amount and price for all markets

fetchOrderBook will returm an orderbook for just one single symbol (market)

> but I get this error: TypeError: 'NoneType' object has no attribute 'getItem'

You need to call

```Python
cryptopia.load_markets()  # load markets before accessing symbols and markets
orderbook = cryptopia.fetch_order_book (cryptopia.symbols[0])
```

↑ this is documented here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Alternatively, this would also work:

```Python
orderbook = cryptopia.fetch_order_book ('ETH/BTC')
```

Hope it answers your question. Thx!

**Comment by l0urdm** [comment]
Hi @kroitor thanks for the reply, its much clearer to me now and apologies for the duplicate

by the way, I would like to suggest in the future update  if its possible to include the bid amount and ask amount in the fetch_tickers()

thanks

**Comment by l0urdm** [comment]
by the way, I checked 'has' for cryptopia and it indeed has fetchOrderBooks = true

but when I try to use it, I get error, please see below

This is my code:

cryptopia.load_markets()
symb = cryptopia.symbols

CR_ORDER_BOOK = cryptopia.fetch_order_books(symb)

print CR_ORDER_BOOK


and below is the error

Traceback (most recent call last):
  File "C:\ccxt_test\cryptopia_test_market_price.py", line 82, in <module>
    CR_ORDER_BOOK = cryptopia.fetch_order_books(symb)
  File "C:\Python27\lib\site-packages\ccxt\cryptopia.py", line 187, in fetch_order_books
    ids = '-'.join(ids)
TypeError: sequence item 0: expected string, int found

**Comment by l0urdm** [comment]
I tried to follow the examples but it still didn't work with python 2.7.14 and still gives me the same error, but I tried it with python 3.6 and it worked like a charm :)

**Comment by kroitor** [comment]
@l0urdm 

1. update ccxt to most recent version 1.10.1137
2. follow the comments from https://github.com/ccxt/ccxt/blob/master/examples/py/cryptopia-fetch-order-books.py

Should work with Python2 as well from there. Let us know if it doesn't.

**Comment by l0urdm** [comment]
yeah, it also worked now. thanks!

**Comment by malcolm1232** [comment]
hi, @kroitor, just wondering how i can get the order book with Timestamps? can be in unix time its ok

**Comment by kroitor** [comment]
@malcolm1232 which specific timestamps do you mean? Very few exchanges serve that info from the orderbook endpoints. You can find the description of the unified orderbook structure in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#order-book-structure

**Comment by malcolm1232** [comment]
@kroitor thank you!! (:
