### ISSUE TITLE
coinbaseprime removed from exchange list

### ISSUE THREAD

**Issue by FlavioFantasy** [ccxt/ccxt#20355]
### Operating System

Ubuntu 22.04.3 LTS

### Programming Languages

Python

### CCXT Version

4.1.87

### Description

Library doesn't have coinbaseprime as exchange anymore on latest version (4.1.87 - 2023-12-13) but raises 
```
AttributeError: module 'ccxt' has no attribute 'coinbaseprime'
```

Code works fine on version `4.1.86` 

### Code

```
import ccxt
exchange = ccxt.coinbaseprime()

```

**Comment by frosty00** [comment]
please use `ccxt.coinbase` instead!

let us know if you have any other issues

**Comment by FlavioFantasy** [comment]
Hi @frosty00, thanks for the help.

Have the maintainers written somewhere this change ? Since 4.1.86 to 4.1.87 it's just a patch update, I wouldn't expect such a removal.

**Comment by frosty00** [comment]
@FlavioFantasy here is the details #20341

**Comment by frosty00** [comment]
I've reverted and relisted coinbase, should arrive soon!
