### ISSUE TITLE
Bitflyer order status

### ISSUE THREAD

**Issue by philipperemy** [ccxt/ccxt#2125]
This feature does not seem to work properly with 1.11.10:

```
print(bitflyer.fetch_order(id='JFX20.....18U', symbol='BTCJPY09MAR2018'))
```

Can somebody advice?

Thanks in advance

**Comment by kroitor** [comment]
> This feature does not seem to work properly with 1.11.10:

Can you elaborate, please? What exactly is wrong? Can you post your complete snippet and your verbose output according to these steps (without the keys): 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

> Can somebody advice?

Without a proper description of the problem it's very hard to guess and help, unfortunately... Standing by for more info from you.

**Comment by philipperemy** [comment]
@kroitor ,

Thanks for helping out. Version is `ccxt (1.11.10)`.

Here is the snippet that is not working:

```
ticker = 'BTCJPY09MAR2018'
ex = bitflyer({'apiKey': API_KEY, 'secret': SECRET})
price = ex.fetch_ticker(ticker)['bid'] - 10000
order = ex.create_limit_buy_order(ticker, 0.001, price)
```

```
print(ex.fetch_order(id=order['id'], symbol=ticker))
# {AuthenticationError}bitflyer https://api.bitflyer.jp/v1/me/getchildorders?product_code=BTCJPY09MAR2018&count=100 GET 401 Client Error: Unauthorized for url: https://api.bitflyer.jp/v1/me/getchildorders?product_code=BTCJPY09MAR2018&count=100 {"status":-500,"error_message":"Invalid signature","data":null}
```

```
print(ex.fetch_order_status(id=order['id']))
# {ExchangeError}bitflyer cancelOrder() requires a symbol argument
```

**Comment by philipperemy** [comment]
@kroitor it's in python, not JS.

Why did you close this issue?

Error 1 is still there and it does not solve error 2...

```
ex.fetch_order_status(id=order['id'], symbol='BTCJPY09MAR2018')
# {TypeError}fetch_order_status() got an unexpected keyword argument 'symbol'
ex.fetch_order_status(id=order['id'], params={'symbol':'BTCJPY09MAR2018'})
# {TypeError}fetch_order_status() got an unexpected keyword argument 'params'
```

**Comment by kroitor** [comment]
> @kroitor it's in python, not JS.

In ccxt Python is generated from JS...  More about it here (if you're interested): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

> Why did you close this issue?

Because I fixed it and the build is on the way, it means "please, be patient, I'll let you know shortly..."

---

Now, the answers and fixes:

1. Update to ccxt v.1.11.1

2. On Error 1: you're need to use rate limiting, otherwise bitflyer won't like it...

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/tree/master/examples/py

3. On Error 2: it isn't very clear, probably, but you need to add a second argument `symbol` to the fetch_order call.

Change your code like so to make it work (after updating to 1.11.11):

```Python
from ccxt import bitflyer
ticker = 'BTCJPY09MAR2018'
ex = bitflyer({
    'apiKey': API_KEY,
    'secret': SECRET,
    'enableRateLimit': True,  # ←------------------ ADD THIS LINE
})

price = ex.fetch_ticker(ticker)['bid'] - 10000 # just make sure it's resting in the order book.
order = ex.create_limit_buy_order(ticker, 0.001, price)

print(ex.fetch_order(id=order['id'], symbol=ticker))

print(ex.fetch_order_status(id=order['id'], symbol=ticker))  # ←------------------- ADD symbol HERE
```

**Comment by philipperemy** [comment]
@kroitor great I'll proceed that way, thanks for the support! Much appreciated!

**Comment by kroitor** [comment]
@philipperemy let us know, if you still have difficulties with it, feel free to reopen this issue or just ask questions, if any.

**Comment by philipperemy** [comment]
@kroitor thank you very much! I will!

**Comment by kroitor** [comment]
@philipperemy P.S. you don't need to fetch order status after fetching the entire order...

```Python
order = ex.fetch_order(id=order['id'], symbol=ticker)  # just one fetch call
print(order)  # this will print the order, including its status
print(order['status'])  # this will print just the order status, no need for a second fetch here
```

You definitely need to read the Manual and to learn more basic Python, also see the examples linked above. That's my strong recommendation to you, it will save you tons of time, really.

**Comment by philipperemy** [comment]
@kroitor yes correct. I just wanted to show the errors. That's why I did that.

**Comment by philipperemy** [comment]
@kroitor With ccxt latest version 
```
ccxt.__version__
'1.11.45'
```

```
from ccxt import bitflyer
ticker = 'BTCJPY09MAR2018'
ex = bitflyer({
    'apiKey': API_KEY,
    'secret': SECRET,
    'enableRateLimit': True,  # ←------------------ ADD THIS LINE
})

price = ex.fetch_ticker(ticker)['bid'] - 10000 # just make sure it's resting in the order book.
order = ex.create_limit_buy_order(ticker, 0.001, price)

print(ex.fetch_order(id=order['id'], symbol=ticker))

print(ex.fetch_order_status(id=order['id'], symbol=ticker))  # ←------------------- ADD symbol HERE
```

I have two exceptions:

`print(ex.fetch_order(id=order['id'], symbol=ticker))`

Triggers:

```
{AuthenticationError}bitflyer https://api.bitflyer.jp/v1/me/getchildorders?product_code=BTC_JPY&count=100 GET 401 Client Error: Unauthorized for url: https://api.bitflyer.jp/v1/me/getchildorders?product_code=BTC_JPY&count=100 {"status":-500,"error_message":"Invalid signature","data":null}
```

```
print(ex.fetch_order_status(id=order['id'], symbol=ticker))
```

Triggers:

```
{TypeError}fetch_order_status() got an unexpected keyword argument 'symbol'
```

**Comment by philipperemy** [comment]
Just for info the problem comes from adding the body in the request.

`self.fetch(request['url'], request['method'], request['headers'], None)`
instead of 
``self.fetch(request['url'], request['method'], request['headers'], request['body'])`

Cf. https://github.com/ccxt/ccxt/issues/1911

Can you propose a fix?

Thanks

**Comment by kroitor** [comment]
@philipperemy I've uploaded a fix, it should arrive in version 1.11.49 in 5-10 minutes. We will be happy if you report back whether you still have a difficulty with it or not. Thank you!

**Comment by philipperemy** [comment]
@kroitor Almost there,

```
print(ex.fetch_order(id=order['id'], symbol=ticker))
```

The call to Bitflyer API is successful but the `def parse_order(self, order, market=None)` returns an error at line 255. `market` is a string and the library tries to `market['symbol']`, which failed.

![image](https://user-images.githubusercontent.com/4516927/37185112-2241261e-2382-11e8-9296-f488e8b53b5e.png)

**Comment by philipperemy** [comment]
@kroitor I've upgraded to `1.11.51` but the line of code and the error are still there.

**Comment by kroitor** [comment]
@philipperemy sorry for the inconvenience, forgot one missing detail, one more fix upcoming...

**Comment by philipperemy** [comment]
Thanks a lot! Just for information, same error `market['symbol']` happens after in `exchange.py` `parse_orders(self, orders, market=None, since=None, limit=None)` line 1096.

Same check should be applied here.

![image](https://user-images.githubusercontent.com/4516927/37186053-caef7744-2386-11e8-934b-b999a5e542d4.png)

**Comment by kroitor** [comment]
@philipperemy yeah, this should be fixed in 1.11.53 in 5-10 minutes.

**Comment by philipperemy** [comment]
@kroitor ok it works! Thanks for the great help!

**Comment by kroitor** [comment]
@philipperemy thx to you for reporting as well ) let us know if you have any other difficulties with it.

**Comment by philipperemy** [comment]
I will thanks )
