### ISSUE TITLE
AttributeError: 'binance' object has no attribute 'publicGetExchangeInfo'

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#4839]
- OS: Windows 10
- Programming Language version: Python 3.7.1
- CCXT version: ccxt-1.18.368
- Exchange: Binance
- Method: fetch_markets

Hi,

I always hit this error when calling fetch_markets for Binance :

**binance.py**
```
    def fetch_markets(self, params={}):
        response = self.publicGetExchangeInfo()
```

=> AttributeError: 'binance' object has no attribute 'publicGetExchangeInfo'

My understanding is that this is not calling an existing method but should be intercepted somehow ?

Can you please help on this one ?

Thank you,
Noel

**Comment by kroitor** [comment]
Hi!

Unfortunately, I'm unable to reproduce the error with this code:

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print(ccxt.__version__)
1.18.368
>>> exchange = ccxt.binance({'enableRateLimit': True})
>>> markets = exchange.fetch_markets()
>>> from pprint import pprint
>>> pprint(markets)
```

↑ Works on my side with Python 3.7.2 on Mac OS X, so, we need more info from you, the vendor of your Python and the code that you're trying to run.

Also, you very rarely have a need to call `fetch_markets()` if ever at all – markets will be loaded automatically anyway – however, if you want to load them, please, read how to do that properly here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Waiting for a followup on this from you.

**Comment by kroitor** [comment]
Feel free to reopen this issue or just ask further questions if you got more )

**Comment by noel45** [comment]
Hi Kroitor,

I work around this issue however I still have it from time to time.
It concerns all the privateGetXXX or publicGetXXX.
I would like to understand deeper how it works :
Because actually when I hit the error "'bitmex' object has no attribute 'publicGetTradeBucketed'" 
well it is actually true that this function does not exist.

So how the function resolution mechanism works ?

Thank you,
Noel

**Comment by kroitor** [comment]
Hi!

> I work around this issue however I still have it from time to time.

Can you make a complete short program (10-20 lines) that would reproduce the issue consistently? We could look into it then, otherwise we will be mostly guessing. We need it to be a complete short script, including instantiation, but without your keys of course. Please follow these guides literally and use markdown for readability: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure to always have the most recent version before you test, though. Version 1.18.368 is quite old by now.

> I would like to understand deeper how it works :
> So how the function resolution mechanism works ?

It is explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods 

And a bit more technically-detailed explanation is also available here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods
