### ISSUE TITLE
ByBit method private_linear_get_position_list

### ISSUE THREAD

**Issue by bestnaf** [ccxt/ccxt#13495]
- OS: Windows
- Programming Language version: Python
- CCXT version: ccxt-1.84.42

Old method I was using (from examples https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-positions.py) stopped working with last vertion:
>>> exchange.private_linear_get_position_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bybit' object has no attribute 'private_linear_get_position_list

Cant find any updated related to it - it is still working on CCXT  1.82.37

**Comment by kroitor** [comment]
@bestnaf you don't have to use the implicit API with bybit anymore, since it now has a unified fetchPositions method, i've updated the example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-positions.py

```Python
# -*- coding: utf-8 -*-

import ccxt

from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets() # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

exchange.verbose = True  # uncomment for debugging

# -----------------------------------------------------------------------------

symbol = 'BTC/USDT:USDT'
market = exchange.market(symbol)
params = {'subType':'linear' if market['linear'] else 'inverse'}
linear_positions = exchange.fetch_positions([ symbol ], params)
pprint(linear_positions)

# -----------------------------------------------------------------------------

symbol = 'BTC/USD:BTC'
market = exchange.market(symbol)
params = {'subType':'linear' if market['linear'] else 'inverse'}
inverse_positions = exchange.fetch_positions([ symbol ], params)
pprint(inverse_positions)

```

**Comment by bestnaf** [comment]
Morning @kroitor 

Just tried the unified calls and there is an issue - it dont return position info, however it gets the reply from exchange if I look into verbose:
>>> markets = exchange.load_markets()
>>> symbol = 'BTC/USDT:USDT'
>>> market = exchange.market(symbol)
>>> params = {'subType':'linear' if market['linear'] else 'inverse'}
>>> linear_positions = exchange.fetch_positions([ symbol ], params)
>>> linear_positions = exchange.fetch_positions(params)
>>> symbol = 'GMT/USDT:USDT'
>>> market = exchange.market(symbol)
>>> params = {'subType':'linear' if market['linear'] else 'inverse'}
>>> linear_positions = exchange.fetch_positions([ symbol ], params)
>>> exchange.verbose = True
>>> linear_positions = exchange.fetch_positions([ symbol ], params)

fetch Request: bybit GET https://api.bybit.com/private/linear/position/list?api_key=b79Qm4xzJeuVv1cNcy&recv_window=5000&subType=linear&symbol=GMTUSDT&timestamp=1653981662232&sign=5c60b84fa1fd5c2277d36906dcf98dea85f863c99295501cd41c9a551b90a8eb RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/private/linear/position/list?api_key=b79Qm4xzJeuVv1cNcy&recv_window=5000&subType=linear&symbol=GMTUSDT&timestamp=1653981662232&sign=5c60b84fa1fd5c2277d36906dcf98dea85f863c99295501cd41c9a551b90a8eb 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1173', 'Server': 'T-GATEWAY', 'Expires': 'Tue, 31 May 2022 07:21:02 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Tue, 31 May 2022 07:21:02 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":[{"user_id":20980824,"symbol":"GMTUSDT","side":"Buy","size":1506,"position_value":1921.0536,"entry_price":1.2756,"liq_price":0.2627,"bust_price":0.2499,"leverage":20,"auto_add_margin":0,"is_isolated":false,"position_margin":784.34522427,"occ_closing_fee":0.22580964,"realised_pnl":0,"cum_realised_pnl":0.11299425,"free_qty":-1506,"tp_sl_mode":"Full","unrealised_pnl":-114.456,"deleverage_indicator":2,"risk_id":1,"stop_loss":0,"take_profit":0,"trailing_stop":0,"position_idx":1,"mode":"BothSide"},{"user_id":20980824,"symbol":"GMTUSDT","side":"Sell","size":753,"position_value":916.5839,"entry_price":1.2172429,"liq_price":199.9998,"bust_price":199.9998,"leverage":20,"auto_add_margin":0,"is_isolated":false,"position_margin":-78.78345498,"occ_closing_fee":90.35990964,"realised_pnl":0,"cum_realised_pnl":17.28946489,"free_qty":753,"tp_sl_mode":"Full","unrealised_pnl":13.2851,"deleverage_indicator":2,"risk_id":1,"stop_loss":0,"take_profit":0,"trailing_stop":0,"position_idx":2,"mode":"BothSide"}],"time_now":"1653981662.431080","rate_limit_status":118,"rate_limit_reset_ms":1653981662428,"rate_limit":120}

**Comment by kroitor** [comment]
Idk where this code is coming from:

>>> markets = exchange.load_markets()
>>> symbol = 'BTC/USDT:USDT'
>>> market = exchange.market(symbol)
>>> params = {'subType':'linear' if market['linear'] else 'inverse'}
>>> linear_positions = exchange.fetch_positions([ symbol ], params)
>>> linear_positions = exchange.fetch_positions(params)
>>> symbol = 'GMT/USDT:USDT'
>>> market = exchange.market(symbol)
>>> params = {'subType':'linear' if market['linear'] else 'inverse'}
>>> linear_positions = exchange.fetch_positions([ symbol ], params)
>>> exchange.verbose = True
>>> linear_positions = exchange.fetch_positions([ symbol ], params)

You are not printing out the positions you're fetching here ↑

Should be something like this:

```Python
# -*- coding: utf-8 -*-

import ccxt

from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets() # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

exchange.verbose = True  # uncomment for debugging

symbol = 'GMT/USDT:USDT'
market = exchange.market(symbol)
params = {'subType':'linear' if market['linear'] else 'inverse'}
inverse_positions = exchange.fetch_positions([ symbol ], params)
pprint(inverse_positions)
```

Let us know if that does not help.

**Comment by bestnaf** [comment]
Oh my, yeah it works if I define the symbol, but it return nothing if I try to make a request without a symbol:
>>> params = {'subType':'linear'}
>>> exchange.fetch_positions(params)
[]
>>> params = {'subType':'inverse'}
>>> exchange.fetch_positions(params)
[]

Is there any way to get all positions data like it was in private implicit method before?
If I try to make a request without params - it returns some random positions data without my open ones

**Comment by kroitor** [comment]
> Oh my, yeah it works if I define the symbol, but it return nothing if I try to make a request without a symbol:
> 
> > > > params = {'subType':'linear'}
> > > > exchange.fetch_positions(params)
> > > > []
> > > > params = {'subType':'inverse'}
> > > > exchange.fetch_positions(params)
> > > > []
> 
> Is there any way to get all positions data like it was in private implicit method before? If I try to make a request without params - it returns some random positions data without my open ones

Use this code:

```Python
# positions = exchange.fetch_positions(params)  # wrong
positions = exchange.fetch_positions(None, params)  # correct
```

**Comment by kroitor** [comment]
@bestnaf how do you initialize the exchange instance?

**Comment by bestnaf** [comment]
> @bestnaf how do you initialize the exchange instance?

exchange_class = getattr(ccxt, 'bybit')
exchange: ccxt.bybit = exchange_class({
'apiKey': API_KEY,
'secret': API_SECRET,
'timeout': 10000,
'enableRateLimit': True,
'rateLimit': 250,
'options': {
'defaultType': 'future',
}
})

also tried to define this separately
exchange.options['defaultType'] = 'future';

results are same

**Comment by kroitor** [comment]
@bestnaf you need `'defaultType': 'swap'`, which is the default...

- https://github.com/ccxt/ccxt/issues/10931
- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

Remove all options from your constructor except the API keys:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
from pprint import pprint
exchange_class = getattr(ccxt, 'bybit')
exchange: ccxt.bybit = exchange_class({
    'apiKey': API_KEY,
    'secret': API_SECRET,
})
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes if necessary
positions = exchange.fetch_positions()
pprint(positions)
```

That should do the trick.

**Comment by bestnaf** [comment]
Yeah it did the trick, thank you!

**Comment by ryanreed357** [comment]
Well help me out then man

**Comment by ryanreed357** [comment]
What exactly is that
