### ISSUE TITLE
Receiving error bittrex exchange class has no attribute 'publicGetOrderbook' when calling fetch_order_book in child process

### ISSUE THREAD

**Issue by IgorMBorushek** [ccxt/ccxt#5762]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.6.3
- CCXT version: 1.18.1112
- Exchange: Bittrex
- Method: fetch_order_book

I normally have no problems on the exchange methods in the main process using the recommended snake_case syntax for python calls, but when I created a child process using Python multiprocess' Process class, the fetch_order_book call returns back 'Bittrex_Local' object has no attribute 'publicGetOrderbook'

Bittrex_Local is my exchange child class that inherits from ccxt.bittrex:
class Bittrex_Local(ccxt.bittrex, Exchange_Mixin_Loc):

It seems like some api_call messages are being reformatted within ccxt somewhere and causing this error? As I said, I don't have this problem in the main process, but in child processes the bittrex.fetch_order_book call does not work.

**Comment by kroitor** [comment]
1. Do you create the exchange in the main process and are you trying to share the exchange instance between processes? Doing that would be bad practice...
2. Can you share more details or paste a minimal snippet of code to reproduce it, so that we would not spend the time guessing? Take your code and start cutting away pieces of it, until you're left with just one file that has the minimal multiprocessing code and demonstrates the issue in 5-10-20 lines. Paste that code in this issue using [markdown](https://guides.github.com/features/mastering-markdown/) for readability as described [here](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue).

**Comment by IgorMBorushek** [comment]
1. I don't have a choice. I have to use a multiprocessing branch of Pathos and with Windows 10, it doesn't carry over any part of the scope outside the function being passed to Process. So everything needs to be passed explicitly to a new process through arguments or inheritance.
2. Excuse me for my inexperience. I attempted to reproduce the issue with minimal code below. Please note that I am on a Windows system. I'm uncertain but there may be no issue running this on a Unix system because it creates new processes through proper forking whereas Windows spawns new processes. Thanks in advance for your attention

```python
#Pathos is Python multiprocessing but replaces Pickle with Dill so you can use it within classes and functions
from pathos.helpers import mp as multiprocess 
import ccxt   

class Trading_Account():
    def __init__(self):
        #Need to reimport here for child process because new processes cannot access any globals unless they're class variables or passed as arguments
        import ccxt
        from pathos.helpers import mp as multiprocess #for multiprocess.Queue
        self.multiprocess = multiprocess
        self.ccxt = ccxt


class Exchange_Mixin_Loc():
    pass    #None of the code is relevant, just wanted to maintain the class MRO so kept this shell class

    
#parent_params are some params used by ccxt.bittrex and ccxt.Exchange that in the ccxt libary, are passed that way.
class Bittrex_Local(ccxt.bittrex, Exchange_Mixin_Loc):
    def __init__(self, TA, parent_params):
        super(Bittrex_Local, self).__init__(parent_params)
        self.TA = TA    #This should really be in exchange_mixin class, but due to the limitations with multiple inheritance not allowing use of init there due to ccxt not being built for it, I have to do it for every exchange specific subclass like this 

#Necessary to start a new process from a main method like this otherwise there are many problems with inheritance and bindings at least with Pathos' multiprocess    
def new_process(exchange):
    print(exchange.fetch_order_book("XMR/BTC", 1000, {"type": "buy"}))
    
    
if __name__ == '__main__':
    TA = Trading_Account()
    
    bittrex = Bittrex_Local(TA, {
    'apiKey': 'caa865e449f84a73931cb1cc20ee36f5',
    'secret': '6bd11c8ba1064d66a3c17bdb6b7d6587',
    'enableRateLimit': True,
    'verbose': True
    })  
    
    #Main process test
    bittrex.load_markets(True)
    print(bittrex.fetch_order_book("XMR/BTC", 1000, {"type": "buy"}))
    
    #Create child process
    p1b = TA.multiprocess.Process(target = new_process, args=(bittrex,))
    p1b.start()```

Below is the error traceback:
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\nt\AppData\Local\Programs\Python\Python36\lib\site-packages\multiprocess\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\nt\AppData\Local\Programs\Python\Python36\lib\site-packages\multiprocess\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nt\Documents\Bots\RobotTrader\Bugtest.py", line 25, in new_process
    print(exchange.fetch_order_book("XMR/BTC", 1000, {"type": "buy"}))
  File "C:\Users\nt\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bittrex.py", line 375, in fetch_order_book
    response = self.publicGetOrderbook(self.extend(request, params))
AttributeError: 'Bittrex_Local' object has no attribute 'publicGetOrderbook'

**Comment by IgorMBorushek** [comment]
Instead of fetch_order_book, inside new_process, you can also try other calls such as fetch_ticker, fetch_closed_orders, etc., they all provide different errors. For example:
fetch_ticker gets: AttributeError: 'Bittrex_Local' object has no attribute 'publicGetMarketsummary'
fetch_closed_orders gets: AttributeError: 'Bittrex_Local' object has no attribute 'v3GetOrdersClosed'

**Comment by kroitor** [comment]
Well...

1. First of, those implicit methods like `publicGetOrderbook` called from inside `fetchOrderBook()` are partial functions:
  - https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

    Partial functions are not real functions, but more like objects saved in memory.

2. Regardless of which OS you're using (Windows, Linux, Mac or whatever) multiprocessing usually cannot easily share memory. The `multiprocessing` module creates a copy of some parts of parents' memory for each new forked process or passes the data that has to be shared among the parents and the children in some other ways. In doing so it applies what is called _"pickling"_.

3. Since partial functions can't be easily pickled, the `publicGetOrderbook` is perfectly visible from your parent process, but not visible inside the child processes. More about it [here](https://stackoverflow.com/questions/45293989/how-to-use-the-partial-function-with-the-python-multiprocessing-module) and [here](https://stackoverflow.com/questions/27318290/why-can-i-pass-an-instance-method-to-multiprocessing-process-but-not-a-multipro).

4. If object memory gets copied upon forking, then, after the fact, the copied pieces of memory are not shared, so, after the fork each of your children will have its own copy of a reference to the exchange class, each having its own copy of the rate limiter not shared across your children. So all subsequent changes to those parts of the memory won't be shared either, unless you pipe the info between your children using pipes or some other form of IPC. In other words, your rate-limiting breaks down, unless you figure out how to share it across your processes.

5. The above issues, apart from the other things are the actual reason why trying to share rate limited exchange instances among child processes isn't the best idea. It's not impossible, and it can be done, though. But you should really reconsider your design with the underlying networking and request rate limitations in mind. Using the `async` functionality is probably the best option in this case, since you won't have to spend the time solving purely-routine multiprocess-engineering problems that are not always related to your main goals directly. Seriously, consider modern ways with `asyncio`.

6. If for some reason, you are unable to use `asyncio` (why couldn't you use it, though), then you want to carefully design the relations between your parent and child processes. You should stress the architectural reasons for initializing an instance in the main process and then sharing it with a child process. If the child process is the only process that will have a reference to that instance, then you should really create the exchange instance itself within the child (not from the parent process).

7. So, in its simplest form, something like this would work:

```Python
from multiprocessing import Process
import ccxt   



def new_process(exchange_id, params={}):
    # create the exchange instance inside the child process and don't share it
    exchange = getattr(ccxt, exchange_id) (params)
    print(exchange.fetch_order_book("XMR/BTC", 1000, {"type": "buy"}))
    


if __name__ == '__main__':
        
    params = {
        'apiKey': 'caa865e449f84a73931cb1cc20ee36f5',
        'secret': '6bd11c8ba1064d66a3c17bdb6b7d6587',
        'enableRateLimit': True,
        'verbose': True
    }
    p1b = Process(target=new_process, args=('bittrex', params))
    p1b.start()

```

If what is written above doesn't really make sense or wouldn't work in your case, then this can still be done right with multiprocessing, but that implies too much of a coding burden to share the resources, bandwidth and memory properly. Would an exclusive non-shared approach work in your case (one exchange per process, each exchange having its own exclusive child) ?

**Comment by IgorMBorushek** [comment]
Thank you for the detailed and thoughtful response. My use case currently doesn't need asyncio or threading, but multiprocessing because it is dealing with cpu-bound tasks. What I am doing is creating an order, a buy, and when it gets partially filled, a child process is created in order to put that partial fill into a sell order simultaneously. Both orders are then doing extensive processing of the order_book and internal logic in order to optimize order placement until they are filled. Furthermore as the buy order gets filled more and more, it continuously shuttles those units into the sell order process.

Furthermore, the above is only for 1 coupled(buy & sell) trade for 1 asset. I need multiprocessing because there are many trades on other assets simultaneously doing extensive cpu-bound calculation. Finally, I want to take advantage of my 16 core system.

To check I understood correctly, you're saying that whether it's forking or spawning, multiprocessing clones all data into child processes? Meaning that, if I wanted to update some data to share between processes, the other processes wouldn't be able to access it because they will have their own local versions? One reason I was sharing exchange instances is I would keep some shared data as exchange variables and use a Queue to control read/write but you are saying this method isn't feasible right because the exchange instance itself is actually cloned and not shared? Could a solution to this be to keep shared data externally in a file and control read/write with a queue? Otherwise I would have to update the local version of the data in each process every time...

I suppose I could create a new exchange instance in each child process, but currently this is impossible because Pathos limits the scoping so I can't even access my exchange child classes for instantiation in child processes, at least that is currently the case with multiprocess.Process. I can try with a Pool but it isn't a great solution because the various trades have to share data such as exchange balances that are updated any time a trade is partially or fully filled, but if I understood how you're saying forking/spawning works then I will have to externalize shared data anyways...

**Comment by kroitor** [comment]
@IgorMBorushek 

> Thank you for the detailed and thoughtful response. My use case currently doesn't need asyncio or threading, but multiprocessing because it is dealing with cpu-bound tasks. 

You should use threads then to have the advantage of your multicore system, because _threads and processes can run concurrently on multi-core CPUs_. 

> Furthermore, the above is only for 1 coupled(buy & sell) trade for 1 asset. I need multiprocessing because there are many trades on other assets simultaneously doing extensive cpu-bound calculation. Finally, I want to take advantage of my 16 core system.

Seriously, use threads. I almost insist. )

> To check I understood correctly, you're saying that whether it's forking or spawning, multiprocessing clones all data into child processes?

No. You need to systematize your understanding of the differences between multiprocessing and multithreading and other forms of concurrency. In general, there are different parts of memory (this comes from [how program memory is layed out deep down in the system](https://en.wikipedia.org/wiki/Data_segment#Program_memory)):

1. your code (business logic, functions, classes)
2. the static memory used in your program less often (strings, literals)
3. the current state of the execution of your program, aka the _"stack"_ (a snapshot of what your program is doing)
4. the dynamic memory used in your program, aka, the _"heap"_ (objects, class instances, variables)

Then you need to understand which parts are shared in Threading mode and compare that to Multiprocessing mode:

Threads: Upon creating a thread, the OS shares 1, 2, 3 and 4 between your parent thread to your child thread. So, child threads can access the memory, variables and class instances that were initialized in the parent thread before the child was created. So, a Queue created in a parent thread will be accessible in all subsequent child threads. And you can reference it in both threads to actually make them _"talk to each other"_, for synchronization purposes, like assigning tasks to child threads from a parent thread. After creating the child, however, the memory is not copied anymore. So, if you create a new variable in a child thread after creating the thread itself, the variable won't be available in the parent and vice versa.

Processes: Upon forking a process, the OS shares 1, 2 and 3, but not 4. So, a reference pointer to a Queue created in the parent process will point to memory that will be locked away from the child process, when the child process tries to access that Queue by dereferencing the pointer. Since those are two different processes, security rules apply, and you can't share the memory between processes, otherwise programs would be able to overwrite each other while running (viruses can often do that, but most often that requires admin permissions anyway). 

> Meaning that, if I wanted to update some data to share between processes, the other processes wouldn't be able to access it because they will have their own local versions? 

Yes, exactly.

> One reason I was sharing exchange instances is I would keep some shared data as exchange variables and use a Queue to control read/write but you are saying this method isn't feasible right because the exchange instance itself is actually cloned and not shared? 

Exactly. You will have to use some form of IPC to allow your processes to talk to each other.

> Could a solution to this be to keep shared data externally in a file and control read/write with a queue? Otherwise I would have to update the local version of the data in each process every time...

Because the dynamic memory is not shared among processes, and also because most of the data used in the program is actually stored on the heap dynamically, multiprocessing people had to invent the whole set of interprocess communication techniques, or IPC, for short. It includes:

- signals (send signals from one to another)
- shared mem (read from and write to the same mem across processes)
- pipes and std IO (listen for bytestreams)
- files and disk IO
- files mapped into memory aka _"mmap'ed files"_
- sockets and networking IO
- databases
- other 

You're asking if file IO can be used for IPC, and yes, it can, not only this is possible, but there's an entire world of its own in there.

> I suppose I could create a new exchange instance in each child process, but currently this is impossible because Pathos limits the scoping so I can't even access my exchange child classes for instantiation in child processes, at least that is currently the case with multiprocess.Process. I can try with a Pool but it isn't a great solution because the various trades have to share data such as exchange balances that are updated any time a trade is partially or fully filled, but if I understood how you're saying forking/spawning works then I will have to externalize shared data anyways...

You should use threads, since that will give you the benefits of your multiple cores without all the hassle of doing complex IPC, since with thread synchronization is a lot easier to manage, really. I could write the sample code that does the proper IPC for you, however, that is far beyond the scope of this lib, since this subject is deeply theoretical, and I can't give you a degree on general CS via GitHub issues, unfortunately. Hope for your understanding, you will have to do the homework, and conduct your research on the terms mentioned above.

Let me know if the above answers your question or not.

**Comment by IgorMBorushek** [comment]
Wow, thanks again. I read about multithreading vs. multiprocessing vs. asyncio. My understanding was that in Python, multithreading and asyncio are meant to only function concurrently within 1 process due to limitations of the GIL. I need a solution to provide effective parallelism for my cpu-bound tasks. You are strongly suggesting threads, but how do I run them over multiple cores in parallel? If you are saying multiprocessing is not the answer, which I am now seeing has serious issues at least with memory sharing thanks to your guidance, then please point me to a more reasonable method of efficiently distributing multiple threads across multiple cpu cores for parallelism.

**Comment by kroitor** [comment]
@IgorMBorushek ah.... pardon, you're right, I forgot that we can't really use threads with Python due to GIL limitations: https://medium.com/practo-engineering/threading-vs-multiprocessing-in-python-7b57f224eadb. So, I'm afraid, you will have to use multiprocessing with some form of IPC anyway.

**Comment by IgorMBorushek** [comment]
Thanks again. I have a final question before I proceed with IPC. When I was creating child processes, the child process could not access global code from the main process such as classes, global imports, etc. You said that among the 4 types of program memory, forked child processes only don't share the 4th type, but it seems like the code would be part of the 1st type. Is this because the process is spawned and not forked on windows or is it some other issue with Pathos? Also, how could I solve that, maybe put all that code into a module and reimport it into child processes?

**Comment by frosty00** [comment]
![Screen Shot 2019-09-07 at 17 53 05](https://user-images.githubusercontent.com/14319357/64481779-63bbd880-d198-11e9-83b8-fb00e1e2126e.png)

@kroitor help with my hw )

**Comment by kroitor** [comment]
@IgorMBorushek 

> but it seems like the code would be part of the 1st type. Is this because the process is spawned and not forked on windows or is it some other issue with Pathos? 

This is not related to Windows or Pathos. This is because the code is only the 1st type, when it is a machine code or assembly code, or code compiled to binary executable that contains CPU instructions and is executed directly by the CPU and the OS. However, with interpreted languages it's a bit more complicated. The code of the Python itself is compiled, so it will run two different interpreter processes just fine. However, when Python interprets your code – it does not store treat is as code. Instead it creates abstractions and objects from your code, so, all your functions and classes become some kinds of objects in terms of Python's internal structuring. All of that goes to dynamic memory if you drill from your code (and how it is interpreted) down to machine code. Your Python code is not really converted to machine code. Your C code is.

> Also, how could I solve that, maybe put all that code into a module and reimport it into child processes?

That's exactly what pickle is trying to do, I think. It's purpose is to take your function-objects and class-objects and serialize them, or, in other words, convert and pack them to arrays of specially-formatted bytes, so that they could be unpacked and recognized by the other process on the receiving end. What you need before trying to invent your own wheel – is to do more research on the existing things and how they work inside in core. It may be so that the solution is just a matter of one command-line option or one compiler option. Or, the solution may turn out to be very hard and to involve a lot of routine with byte-packing. Consider this: when you have a problem related to programming or development – there's a very high chance that someone else has already encountered the same problem and maybe even solved it successfully in a distributable package...

Let me know if that does not answer the question. )
